### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by ghost** [Auctionator/BCC-Auctionator#1]
Message: Interface\AddOns\Auctionator\Auctionator-2.5.1.lua:631: attempt to index field 'RecipeList' (a nil value)
Time: Sat Jun 12 19:24:27 2021
Count: 1
Stack: Interface\AddOns\Auctionator\Auctionator-2.5.1.lua:631: attempt to index field 'RecipeList' (a nil value)

Locals:

**Comment by plusmouse** [comment]
Find the fix in 2.5.2 https://www.curseforge.com/wow/addons/auctionator/files/3349258
